# Generated by Django 3.2.9 on 2021-11-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=191, null=True)),
                ('username', models.CharField(max_length=191)),
                ('first_name', models.CharField(blank=True, max_length=191, null=True)),
                ('last_name', models.CharField(blank=True, max_length=191, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=191, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
                ('is_banned', models.IntegerField(blank=True, null=True)),
                ('ban_reason', models.CharField(blank=True, max_length=191, null=True)),
                ('skip_onboarding', models.IntegerField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('has_email_verified', models.IntegerField(blank=True, null=True)),
                ('has_mobile_number_verified', models.IntegerField(blank=True, null=True)),
                ('is_journal_entry_created', models.IntegerField()),
                ('my_referral_code', models.CharField(blank=True, max_length=191, null=True)),
                ('api_version', models.CharField(blank=True, max_length=191, null=True)),
                ('mobile_app_version', models.IntegerField(blank=True, null=True)),
                ('source_of_registration', models.CharField(blank=True, max_length=200, null=True)),
                ('is_disabled', models.IntegerField()),
                ('disabled_reason', models.TextField(blank=True, null=True)),
                ('email_verification_status', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_data_migrated', models.IntegerField(blank=True, null=True)),
                ('is_migration_notified', models.IntegerField(blank=True, null=True)),
                ('user_role_in_company', models.CharField(blank=True, max_length=200, null=True)),
                ('social_login_providers_id', models.IntegerField()),
                ('client_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('is_user_used_app_migrated', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
